vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set('n', '<c-z>', '<nop>')
vim.keymap.set('i', '<c-c>', 'Ç')
vim.keymap.set('i', '<c-e>', '<Esc>')
vim.keymap.set('i', '<c-x><c-s>', '<Esc>:w<CR>a')
vim.keymap.set('n', '<c-x><c-s>', '<Esc>:w<CR>')
vim.keymap.set('n', '<c-s><c-y>', ':ThesaurusQueryReplaceCurrentWord<CR>')
vim.keymap.set('n', 'gn', ':tabnew<Space>')
vim.keymap.set('n', 't', 'F')
vim.keymap.set('n', 'F', 't')
vim.keymap.set('i', '&à', 'À')
vim.keymap.set('i', '&é', 'É')
--vim.keymap.set('n', '<c-c><c-l>', ':!pdflatex %<CR>')
--vim.keymap.set('n', '<c-c><c-b>', ':!biber --isbn-normalise %:r<CR>')
vim.keymap.set('n', 'zz', '1z=')
vim.keymap.set('i', '.', '.<c-g>u')
vim.keymap.set('i', ',', ',<c-g>u')
vim.keymap.set('i', ':', ':<c-g>u')
vim.keymap.set('i', ';', ';<c-g>u')
vim.keymap.set('i', '!', '!<c-g>u')
vim.keymap.set('i', '?', '?<c-g>u')
vim.keymap.set('i', '(', '<c-g>u(')
vim.keymap.set('i', ')', '<c-g>u)')
vim.keymap.set('n', 'zv', '[s')
vim.keymap.set('n', 'zs', ']s')
