vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.mouse = 'a'
vim.opt.showmode = false
vim.opt.clipboard = 'unnamedplus'
vim.opt.breakindent = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.signcolumn = 'yes'
vim.opt.updatetime = 250
vim.opt.timeoutlen = 300
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.inccommand = 'split'
vim.opt.virtualedit = 'block'
vim.opt.cursorline = true
vim.opt.linebreak = true
vim.opt.hlsearch = true
vim.opt.foldenable = false
vim.opt.spell = true
vim.opt.spelllang = {'fr', 'en_gb'}
vim.opt.termguicolors = true
